# Name: Rawan Mohamed Said         
# ID: 4

# **Pandas and Numpy Assignment**

This Assignment will test your abilities in pandas & numpy libraries , feel free to search up and ask if you struggled with something, good luck!

### **Start by importing the libraries**

In [1]:
import numpy as np
import pandas as pd

#**Numpy**

##**Creating Arrays**

###**Create an array of random numbers from 50 to 100 of size 2*3**

###**Generate a 3*3 identity matrix**

In [2]:
#Array of random numbers from 50 to 100 inclusive of size 2*3
rand_arr = np.random.randint(50,101,(2,3))
rand_arr

array([[61, 79, 61],
       [51, 57, 70]])

In [3]:
#Identity matrix of size 3*3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##**Array Operations**

###**Find the dot product between the given arrays:**

In [4]:
# Data:
 #[ 57  55   4  85 -88].[[-24 -27  28  25  47]]
 #[[19 91 36],[-74 -42  48],[19 -51 -83]]*[[-89 -10 -75],[-84 -25 -10],[-96   0  44]]

a = np.array([57, 55, 4, 85, -88])
b = np.array([-24, -27, 28, 25, 47])
c = np.array([[19, 91, 36],[-74, -42, 48],[19, -51, -83]])
d = np.array([[-89, -10, -75],[-84, -25, -10],[-96, 0, 44]])

result_1 = np.dot(a,b)
result_2 = np.dot(c,d)

print(result_1, '\n')
print(result_2)

-4752

[[-12791  -2465   -751]
 [  5506   1790   8082]
 [ 10561   1085  -4567]]

##**Create a 4X4 random array with mean =1.5 and standerd deviation = 4,then re-shape it into 2X8 array**

In [5]:
arr = np.random.normal(1.5, 4, (4,4))  #normal(loc=mean, scale=std_dev, size)
print(arr,'\n')

arr_reshaped = arr.reshape(2,8)
print(arr_reshaped)

[[-0.23444494  0.89009231  3.67237815  9.94346784]
 [-1.55141863  2.10121451  5.07546597  5.44343856]
 [-0.44479397  3.41242756 -3.01727936  5.23311985]
 [-6.06161802 -0.40172002  5.97296641  1.45001346]]

[[-0.23444494  0.89009231  3.67237815  9.94346784 -1.55141863  2.10121451
   5.07546597  5.44343856]
 [-0.44479397  3.41242756 -3.01727936  5.23311985 -6.06161802 -0.40172002
   5.97296641  1.45001346]]

### **Given this 1D array , add a new dimension , then flat it back into 1D**

In [6]:
#[  79 -130   94   53   84 -175 -146 -105  169   81]

In [7]:
array = np.array([79, -130, 94, 53, 84, -175, -146, -105, 169, 81])
array = array[:, np.newaxis]
print(array, '\n')

array = array.reshape(-1)
print(array)

[[  79]
 [-130]
 [  94]
 [  53]
 [  84]
 [-175]
 [-146]
 [-105]
 [ 169]
 [  81]]

[  79 -130   94   53   84 -175 -146 -105  169   81]

# **Great Job :D**

# **Pandas**

### **Import the given csv file**

In [8]:
data = pd.read_csv('Assignment.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## **Exploring**

### **Start by printing the shape of the data**

In [9]:
data.shape

(10000, 14)

### **Printing the data using head and tail**

In [10]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
data.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### **Now, print some basic information about your data columns."use any function you want"**

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [13]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

## **Searching**

###**Use ANY FUNCTION to search up for people with surname 'Hill' And count how many rows with this surname**

In [14]:
hill = data[data['Surname'] == 'Hill']
hill.shape[0]

17

### **Use functions to get the mean balance for users from Spain who are active and have more than one product.**

In [15]:
users = data[(data['Geography']=='Spain') & (data['IsActiveMember']==1) & (data['NumOfProducts']>1)]
users['Balance'].mean()

31722.024068857587

## **Modifying columns.**

### **Change every value in coloumn:"HasCrCard" into True if it's 1 and False if it's 0.**

In [16]:
data['HasCrCard'].replace(1, 'True', inplace=True)
data['HasCrCard'].replace(0, 'False', inplace=True)
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,True,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,False,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,True,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,False,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,True,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,True,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,True,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,False,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,True,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,True,0,38190.78,0

### **Add a new coloumn to data named "Rich" ,it should be as follows :**
### **If the customer has more than 5k in his balance and active and has a credit card and the estimated salary is lower than <= the balance ,then he's rich.**
### **Else , he's not rich.**

In [17]:
data['Rich'] = np.where((data['Balance']>5000) & (data['IsActiveMember']==1) & (data['HasCrCard']==1) &(data['EstimatedSalary']<=data['Balance']),'True','False')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Rich
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,True,1,101348.88,1,False
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,False,1,112542.58,0,False
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,True,0,113931.57,1,False
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,False,0,93826.63,0,False
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,True,1,79084.10,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,True,0,96270.64,0,False
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,True,1,101699.77,0,False
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,False,1,42085.58,1,False
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,True,0,92888.52,1,False
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,True,0,38190.78,0,False

# **Good Luck !!**